add_library(arengine_audio STATIC src/Audio.cpp)
add_library(AREngine::Audio ALIAS arengine_audio)
target_include_directories(arengine_audio PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(arengine_audio PUBLIC AREngine::Core)
target_compile_features(arengine_audio PUBLIC cxx_std_20)
if(MSVC)
    target_compile_options(arengine_audio PRIVATE /W4 /WX)
endif()
if(ARENGINE_ENABLE_AUDIO)
    add_library(arengine_miniaudio STATIC src/Miniaudio.cpp)
    target_include_directories(arengine_miniaudio SYSTEM PUBLIC ${PROJECT_SOURCE_DIR}/third_party/miniaudio)
    target_compile_definitions(arengine_miniaudio PUBLIC MA_NO_RESOURCE_MANAGER MA_NO_DECODING MA_NO_ENCODING MA_NO_GENERATION MA_NO_NULL)
    if(MSVC)
        target_compile_options(arengine_miniaudio PRIVATE /W0)
    endif()
    target_sources(arengine_audio PRIVATE src/AudioContext.cpp)
    target_link_libraries(arengine_audio PRIVATE arengine_miniaudio)
endif()
